env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
  - '@nuxtjs/eslint-config-typescript'
overrides: []
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser:
    ts: '@typescript-eslint/parser'
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  semi: [error, always],
  '@typescript-eslint/no-unused-vars': [
    'error',
    {
      argsIgnorePattern: ^_
    }
  ],
  no-tabs: off,
  indent: [error, tab],
  space-before-function-paren: off,
  arrow-parens: off,
  quotes: off,
  vue/html-indent: off,
  vue/singleline-html-element-content-newline: off,
  vue/multi-word-component-names: off,
  vue/no-setup-props-destructure: off
}
